site_name: Flameshot
site_url: 'https://flameshot.org'
repo_url: 'https://github.com/flameshot-org/flameshot'
edit_uri: '' # hide edit button
site_dir: 'guide'
site_description: 'The official flameshot site.'
site_author: 'The flameshot org.'
copyright: 'Copyright &copy; 2017 ~ 2021 The flameshot org.'

# NOTE. mkdocs will auto-generate navigation when here is no nav configuration.
# https://squidfunk.github.io/mkdocs-material
nav:
    - Overview: index.md
    - Guide:
      - Installation: guide/installation/installation-index.md
      - Key Bindings: guide/key-bindings.md
      - Troubleshooting: guide/troubleshooting.md
      - FAQ: guide/faq.md
      - Issue Reporting: guide/issue-reporting.md
    - Advanced:
      - Configuration: advanced/configuration.md
      - Command Line Options: advanced/command-line-options.md
    - More:
      - Translation:  more/translation.md
    - Changelog: changelog.md

theme:
  name: material
  language: en
  favicon: media/favicon.png
  logo: media/flameshot.svg
  palette:
    # default or slate
    scheme: default
    primary: indigo
    accent: deep purple
  # google font: https://fonts.google.com
  font:
    code: Fira Code

# Extensions
# Arithmatex: https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/flameshot-org
      name: flameshot-org on Github
    - icon: fontawesome/brands/slack
      link: flameshotworkspace.slack.com/
      name: Flameshot Slack Workspace
