name: Zola on GitHub Pages

on:
  push:
    branches:
      - master
      - dev-docs
  pull_request:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3.0.0
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.16.1-1
        env:
          BUILD_DIR: .
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy developer docs
        working-directory: ${{github.workspace}}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions-bot@users.noreply.github.com"

          git fetch origin gh-pages:gh-pages developer-docs:developer-docs
          git checkout gh-pages
          git cherry-pick developer-docs || true
          git remote add destination "https://${{github.actor}}:${{github.token}}@github.com/${{github.repository}}.git"
          git push destination gh-pages
